easy_admin:
    entities:
        CarouselTipo:
            class: AppBundle\Entity\CarouselTipo
        Habitacion:
            class: AppBundle\Entity\Habitacion
        HabitacionTipo:
            class: AppBundle\Entity\HabitacionTipo
        PageCarousel:
            class: AppBundle\Entity\PageCarousel
            list:
                fields:
                    - id
                    - { property: 'url', type: 'image', base_path: %app.path.carousel_images% }
                    - pagina
                    - orden
                    - activo
                    - titulo
                    - captionText
                    - promocion
                    - link
            show:
                fields:
                    - id
                    - { property: 'url', type: 'image', base_path: %app.path.carousel_images% }
                    - pagina
                    - orden
                    - activo
                    - titulo
                    - captionText
                    - promocion
                    - link
                    - modificador
                    - updatedAt
            form:
                fields:
                    - pagina
                    - carouselTipo
                    - orden
                    - activo
                    - titulo
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'captionText', type: 'text', label: 'Descripción'}
                    - link
                    - promocion
        Promocion:
            class: AppBundle\Entity\Promocion
            list:
                fields:
                    - id
                    - nombre
                    - slug
                    - fechaInicio
                    - fechaTermino
                    - portada
                    - template
                    - opcion1Nombre
                    - opcion2Nombre
            show:
                fields:
                    - id
                    - nombre
                    - slug
                    - fechaInicio
                    - fechaTermino
                    - portada
                    - template
                    - opcion1Nombre
                    - opcion2Nombre
                    - modificador
                    - updatedAt
            form:
                fields:
                    - nombre
                    - fechaInicio
                    - fechaTermino
                    - portada
                    - template
                    - opcion1Nombre
                    - opcion2Nombre
        PromocionXHabitacion:
            class: AppBundle\Entity\PromocionXHabitacion
            list:
                fields:
                    - id
                    - promocion
                    - habitacion
                    - vendida
                    - pesoOpcion1
                    - pesoOpcion2
                    - dolarOpcion1
                    - dolarOpcion2
            show:
                fields:
                    - id
                    - promocion
                    - habitacion
                    - vendida
                    - pesoOpcion1
                    - pesoOpcion2
                    - dolarOpcion1
                    - dolarOpcion2
            form:
                fields:
                    - promocion
                    - habitacion
                    - vendida
                    - pesoOpcion1
                    - pesoOpcion2
                    - dolarOpcion1
                    - dolarOpcion2
        Tarifa:
            class: AppBundle\Entity\Tarifa
            list:
                fields:
                    - id
                    - temporada
                    - habitacionTipo
                    - pesoSemana
                    - pesoFinde
                    - dolarSemana
                    - dolarFinde
            form:
                fields:
                    - temporada
                    - habitacionTipo
                    - pesoSemana
                    - pesoFinde
                    - dolarSemana
                    - dolarFinde
        Temporada:
            class: AppBundle\Entity\Temporada
            form:
                fields:
                    - nombre
                    - activa
