easy_admin:
    site_name: 'Hotel Sutherland'
    entities:
        Contacto:
            class: AppBundle\Entity\Contacto
            list:
                fields:
                    - id
                    - updatedAt
                    - fullName
                    - paisNombre
                    - email
                    - telefono
                    - asunto
                    - mensaje
                actions: ["-edit","-delete","show"]
        Opinion:
            class: AppBundle\Entity\Opinion
            list:
                fields:
                    - id
                    - valorizacion
                    - usuario
                    - fecha
                    - opinion
                    - loMejor
                    - porMejorar
                    - respuesta
                actions: ["-delete","show"]
            form:
                fields:
                    - respuesta
        Promocion:
            class: AppBundle\Entity\Promocion
            list:
                fields:
                    - id
                    - nombre
                    - slug
                    - fechaInicio
                    - fechaTermino
                    - portada
                    - template
                    - opcion1Nombre
                    - opcion2Nombre
                    - camaAdicional
            show:
                fields:
                    - id
                    - nombre
                    - slug
                    - fechaInicio
                    - fechaTermino
                    - portada
                    - template
                    - opcion1Nombre
                    - opcion2Nombre
                    - camaAdicional
                    - modificador
                    - updatedAt
            form:
                fields:
                    - nombre
                    - fecha
                    - fechaInicio
                    - fechaTermino
                    - portada
                    - { property: 'imageFile', type: 'vich_image' }
                    - template
                    - opcion1Nombre
                    - opcion2Nombre
                    - { property: 'camaAdicional', help: 'Valor en USD' }
        PageCarousel:
            class: AppBundle\Entity\PageCarousel
            list:
                fields:
                    - id
                    - { property: 'url', type: 'image', base_path: %app.path.carousel_images% }
                    - pagina
                    - orden
                    - activo
                    - titulo
                    - captionText
                    - promocion
                    - link
            show:
                fields:
                    - id
                    - { property: 'url', type: 'image', base_path: %app.path.carousel_images% }
                    - pagina
                    - orden
                    - activo
                    - titulo
                    - captionText
                    - promocion
                    - link
                    - modificador
                    - updatedAt
            form:
                fields:
                    - { property: 'pagina', help: 'Valores posibles: portada, faq, habitacion, tarifa, eco-amigo, o titulo-del-post-del-blog' }
                    - carouselTipo
                    - orden
                    - activo
                    - titulo
                    - { property: 'imageFile', type: 'vich_image', help: 'Dimensiones: 4032 x 2400' }
                    - { property: 'captionText', type: 'text', label: 'Descripción'}
                    - link
                    - promocion
        Tarifa:
            class: AppBundle\Entity\Tarifa
            list:
                fields:
                    - id
                    - temporada
                    - habitacionTipo
                    - pesoSemana
                    - pesoFinde
                    - dolarSemana
                    - dolarFinde
            form:
                fields:
                    - temporada
                    - habitacionTipo
                    - pesoSemana
                    - pesoFinde
                    - dolarSemana
                    - dolarFinde
        Temporada:
            class: AppBundle\Entity\Temporada
            form:
                fields:
                    - nombre
                    - activa
        PromocionXHabitacion:
            class: AppBundle\Entity\PromocionXHabitacion
            list:
                fields:
                    - id
                    - promocion
                    - habitacion
                    - vendida
                    - pesoOpcion1
                    - pesoOpcion2
                    - dolarOpcion1
                    - dolarOpcion2
            show:
                fields:
                    - id
                    - promocion
                    - habitacion
                    - vendida
                    - pesoOpcion1
                    - pesoOpcion2
                    - dolarOpcion1
                    - dolarOpcion2
            form:
                fields:
                    - promocion
                    - habitacion
                    - vendida
                    - pesoOpcion1
                    - pesoOpcion2
                    - dolarOpcion1
                    - dolarOpcion2
        Faq:
            class: AppBundle\Entity\Faq
            list:
                fields:
                    - orden
                    - pregunta
                    - respuesta
            form:
                fields:
                    - orden
                    - pregunta
                    - respuesta
        CarouselTipo:
            class: AppBundle\Entity\CarouselTipo
        Habitacion:
            class: AppBundle\Entity\Habitacion
        HabitacionTipo:
            class: AppBundle\Entity\HabitacionTipo
            list:
                fields:
                    - id
                    - { property: 'url', type: 'image', base_path: %app.path.habitacion_tipo_images% }
                    - nombre
                    - galeria
            form:
                fields:
                    - nombre
                    - orden
                    - descripcion
                    - { property: 'imageFile', type: 'vich_image' }
                    - galeria

        Galeria:
            class: AppBundle\Entity\Galeria
            list:
                fields:
                    - id
                    - nombre
                    - prioridad
                    - portada
                    - { property: 'url', type: 'image', base_path: %app.path.galeria_muestra_images% }
                    - galeriaItem
            form:
                fields:
                    - nombre
                    - prioridad
                    - portada
                    - { property: 'imageFile', type: 'vich_image', label: 'Imagen Muestra' }
        GaleriaItem:
            class: AppBundle\Entity\GaleriaItem
            list:
                fields:
                    - id
                    - tipo
                    - titulo
                    - { property: 'urlMiniatura', type: 'image', base_path: %app.path.galeria_miniatura_images% }
                    - galeria
                    - referencia
                    - url
            form:
                fields:
                    - { property: 'tipo', type: 'choice', type_options: {'choices' : {"imagen" : "imagen", "video" : "video", "youtube" : "youtube", "vimeo" : "vimeo"}}}
                    - titulo
                    - { property: 'referencia', help: 'Id de video de youtube o vimeo'}
                    - { property: 'imageFile', type: 'vich_image', label: 'Imagen o Video' }
                    - { property: 'imageFileMin', type: 'vich_image', label: 'Miniatura' }
                    - galeria
