CREATE TABLE USUARIO (
 id BIGSERIAL,
 nombres VARCHAR(100),
 apellido_paterno VARCHAR(50),
 apellido_materno VARCHAR(50)
);


ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_pkey PRIMARY KEY (id);

CREATE TABLE PAGE_CAROUSEL (
 id BIGSERIAL,
 pagina VARCHAR(100),
 orden INTEGER NOT NULL,
 carousel_tipo_id INTEGER,
 promocion_id INTEGER,
 url VARCHAR(255) NOT NULL,
 caption_text MEDIUMTEXT,
 activo bit NOT NULL DEFAULT true,
 updated_at DATETIME,
 modificador_id INTEGER,
 titulo VARCHAR(150),
 link VARCHAR(255)
);


ALTER TABLE PAGE_CAROUSEL ADD CONSTRAINT PAGE_CAROUSEL_pkey PRIMARY KEY (id);
ALTER TABLE PAGE_CAROUSEL ADD CONSTRAINT PAGE_CAROUSEL_carousel_tipo_id_fkey FOREIGN KEY (carousel_tipo_id) REFERENCES CAROUSEL_TIPO(id);
ALTER TABLE PAGE_CAROUSEL ADD CONSTRAINT PAGE_CAROUSEL_promocion_id_fkey FOREIGN KEY (promocion_id) REFERENCES PROMOCION(id);
ALTER TABLE PAGE_CAROUSEL ADD CONSTRAINT PAGE_CAROUSEL_modificador_id_fkey FOREIGN KEY (modificador_id) REFERENCES USUARIO(id);

CREATE TABLE CAROUSEL_TIPO (
 id BIGSERIAL,
 nombre VARCHAR(15) NOT NULL,
 template VARCHAR(50) NOT NULL
);


ALTER TABLE CAROUSEL_TIPO ADD CONSTRAINT CAROUSEL_TIPO_pkey PRIMARY KEY (id);

CREATE TABLE HABITACION_TIPO (
 id BIGSERIAL,
 nombre VARCHAR(200) NOT NULL
);


ALTER TABLE HABITACION_TIPO ADD CONSTRAINT HABITACION_TIPO_pkey PRIMARY KEY (id);

CREATE TABLE HABITACION (
 id BIGSERIAL,
 nombre VARCHAR(50) NOT NULL,
 habitacion_tipo_id INTEGER NOT NULL
);


ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_pkey PRIMARY KEY (id);
ALTER TABLE HABITACION ADD CONSTRAINT HABITACION_habitacion_tipo_id_fkey FOREIGN KEY (habitacion_tipo_id) REFERENCES HABITACION_TIPO(id);

CREATE TABLE TEMPORADA (
 id BIGSERIAL,
 nombre VARCHAR(255) NOT NULL,
 activa bit NOT NULL DEFAULT true,
 modificador_id INTEGER,
 updated_at DATETIME
);


ALTER TABLE TEMPORADA ADD CONSTRAINT TEMPORADA_pkey PRIMARY KEY (id);
ALTER TABLE TEMPORADA ADD CONSTRAINT TEMPORADA_modificador_id_fkey FOREIGN KEY (modificador_id) REFERENCES USUARIO(id);

CREATE TABLE TARIFA (
 id BIGSERIAL,
 temporada_id INTEGER NOT NULL,
 habitacion_tipo_id INTEGER NOT NULL,
 peso_semana INTEGER,
 peso_finde INTEGER,
 dolar_semana INTEGER,
 dolar_finde INTEGER,
 modificador_id INTEGER,
 updated_at DATETIME
);


ALTER TABLE TARIFA ADD CONSTRAINT TARIFA_pkey PRIMARY KEY (id);
ALTER TABLE TARIFA ADD CONSTRAINT TARIFA_pkey UNIQUE (temporada_id, habitacion_tipo_id);
ALTER TABLE TARIFA ADD CONSTRAINT TARIFA_temporada_id_fkey FOREIGN KEY (temporada_id) REFERENCES TEMPORADA(id);
ALTER TABLE TARIFA ADD CONSTRAINT TARIFA_habitacion_tipo_id_fkey FOREIGN KEY (habitacion_tipo_id) REFERENCES HABITACION_TIPO(id);
ALTER TABLE TARIFA ADD CONSTRAINT TARIFA_modificador_id_fkey FOREIGN KEY (modificador_id) REFERENCES USUARIO(id);

CREATE TABLE PROMOCION (
 id BIGSERIAL,
 nombre VARCHAR(255) NOT NULL,
 template VARCHAR(255),
 fecha_inicio DATETIME,
 fecha_termino DATETIME,
 portada bit NOT NULL DEFAULT true,
 opcion_1_nombre VARCHAR(255),
 opcion_2_nombre VARCHAR(255),
 modificador_id INTEGER,
 updated_at DATETIME,
 slug VARCHAR(255),
 url VARCHAR(255),
 fecha DATE
);


ALTER TABLE PROMOCION ADD CONSTRAINT PROMOCION_pkey PRIMARY KEY (id);
ALTER TABLE PROMOCION ADD CONSTRAINT PROMOCION_pkey UNIQUE (slug);
ALTER TABLE PROMOCION ADD CONSTRAINT PROMOCION_modificador_id_fkey FOREIGN KEY (modificador_id) REFERENCES USUARIO(id);

CREATE TABLE PROMOCION_x_HABITACION (
 id BIGSERIAL,
 promocion_id INTEGER,
 habitacion_id INTEGER,
 vendida bit NOT NULL DEFAULT false,
 peso_opcion_1 INTEGER,
 peso_opcion_2 INTEGER,
 dolar_opcion_1 INTEGER,
 dolar_opcion_2 INTEGER
);


ALTER TABLE PROMOCION_x_HABITACION ADD CONSTRAINT PROMOCION_x_HABITACION_pkey PRIMARY KEY (id);
ALTER TABLE PROMOCION_x_HABITACION ADD CONSTRAINT PROMOCION_x_HABITACION_promocion_id_fkey FOREIGN KEY (promocion_id) REFERENCES PROMOCION(id);
ALTER TABLE PROMOCION_x_HABITACION ADD CONSTRAINT PROMOCION_x_HABITACION_habitacion_id_fkey FOREIGN KEY (habitacion_id) REFERENCES HABITACION(id);