DROP TABLE IF EXISTS USUARIO CASCADE;
DROP TABLE IF EXISTS PAGE_CAROUSEL CASCADE;
DROP TABLE IF EXISTS CAROUSEL_TIPO CASCADE;
DROP TABLE IF EXISTS HABITACION_TIPO CASCADE;
DROP TABLE IF EXISTS HABITACION CASCADE;
DROP TABLE IF EXISTS TEMPORADA CASCADE;
DROP TABLE IF EXISTS TARIFA CASCADE;
DROP TABLE IF EXISTS PROMOCION CASCADE;
DROP TABLE IF EXISTS PROMOCION_x_HABITACION CASCADE;
CREATE TABLE USUARIO (
  "id"  SERIAL ,
  "nombres" VARCHAR(100) ,
  "apellido_paterno" VARCHAR(50) ,
  "apellido_materno" VARCHAR(50) ,
  PRIMARY KEY ("id")
);

CREATE TABLE PAGE_CAROUSEL (
  "id"  SERIAL ,
  "pagina" VARCHAR(100) ,
  "orden" INTEGER NOT NULL ,
  "carousel_tipo_id" INTEGER ,
  "promocion_id" INTEGER ,
  "url" VARCHAR(255) NOT NULL ,
  "caption_text" TEXT ,
  "activo" BOOLEAN NOT NULL DEFAULT true ,
  "updated_at" TIMESTAMP ,
  "modificador_id" INTEGER ,
  "titulo" VARCHAR(150) ,
  "link" VARCHAR(255) ,
  PRIMARY KEY ("id")
);

CREATE TABLE CAROUSEL_TIPO (
  "id"  SERIAL ,
  "nombre" VARCHAR(15) NOT NULL ,
  "template" VARCHAR(50) NOT NULL ,
  PRIMARY KEY ("id")
);

CREATE TABLE HABITACION_TIPO (
  "id"  SERIAL ,
  "nombre" VARCHAR(200) NOT NULL ,
  PRIMARY KEY ("id")
);

CREATE TABLE HABITACION (
  "id"  SERIAL ,
  "nombre" VARCHAR(50) NOT NULL ,
  "habitacion_tipo_id" INTEGER NOT NULL ,
  PRIMARY KEY ("id")
);

CREATE TABLE TEMPORADA (
  "id"  SERIAL ,
  "nombre" VARCHAR(255) NOT NULL ,
  "activa" BOOLEAN NOT NULL DEFAULT true ,
  "modificador_id" INTEGER ,
  "updated_at" TIMESTAMP ,
  PRIMARY KEY ("id")
);

CREATE TABLE TARIFA (
  "id"  SERIAL ,
  "temporada_id" INTEGER NOT NULL ,
  "habitacion_tipo_id" INTEGER NOT NULL ,
  "peso_semana" INTEGER ,
  "peso_finde" INTEGER ,
  "dolar_semana" INTEGER ,
  "dolar_finde" INTEGER ,
  "modificador_id" INTEGER ,
  "updated_at" TIMESTAMP ,
  PRIMARY KEY ("id"),
  UNIQUE ("temporada_id", "habitacion_tipo_id")
);

CREATE TABLE PROMOCION (
  "id"  SERIAL ,
  "nombre" VARCHAR(255) NOT NULL ,
  "template" VARCHAR(255) ,
  "fecha_inicio" TIMESTAMP ,
  "fecha_termino" TIMESTAMP ,
  "portada" BOOLEAN NOT NULL DEFAULT true ,
  "opcion_1_nombre" VARCHAR(255) ,
  "opcion_2_nombre" VARCHAR(255) ,
  "modificador_id" INTEGER ,
  "updated_at" TIMESTAMP ,
  "slug" VARCHAR(255) ,
  PRIMARY KEY ("id"),
  UNIQUE ("slug")
);

CREATE TABLE PROMOCION_x_HABITACION (
  "id"  SERIAL ,
  "promocion_id" INTEGER ,
  "habitacion_id" INTEGER ,
  "vendida" BOOLEAN NOT NULL DEFAULT false ,
  "peso_opcion_1" INTEGER ,
  "peso_opcion_2" INTEGER ,
  "dolar_opcion_1" INTEGER ,
  "dolar_opcion_2" INTEGER ,
  PRIMARY KEY ("id")
);

ALTER TABLE PAGE_CAROUSEL ADD FOREIGN KEY ("carousel_tipo_id") REFERENCES CAROUSEL_TIPO ("id");
ALTER TABLE PAGE_CAROUSEL ADD FOREIGN KEY ("promocion_id") REFERENCES PROMOCION ("id");
ALTER TABLE PAGE_CAROUSEL ADD FOREIGN KEY ("modificador_id") REFERENCES USUARIO ("id");
ALTER TABLE HABITACION ADD FOREIGN KEY ("habitacion_tipo_id") REFERENCES HABITACION_TIPO ("id");
ALTER TABLE TEMPORADA ADD FOREIGN KEY ("modificador_id") REFERENCES USUARIO ("id");
ALTER TABLE TARIFA ADD FOREIGN KEY ("temporada_id") REFERENCES TEMPORADA ("id");
ALTER TABLE TARIFA ADD FOREIGN KEY ("habitacion_tipo_id") REFERENCES HABITACION_TIPO ("id");
ALTER TABLE TARIFA ADD FOREIGN KEY ("modificador_id") REFERENCES USUARIO ("id");
ALTER TABLE PROMOCION ADD FOREIGN KEY ("modificador_id") REFERENCES USUARIO ("id");
ALTER TABLE PROMOCION_x_HABITACION ADD FOREIGN KEY ("promocion_id") REFERENCES PROMOCION ("id");
ALTER TABLE PROMOCION_x_HABITACION ADD FOREIGN KEY ("habitacion_id") REFERENCES HABITACION ("id");